apiKey: <your twickets api key> # MUST be set. See README.md for detail on how to obtain

country: GB # Currently only GB is supported

# Configure your notification services.
# Delete the ones you do not need.
notification:
  ntfy:
    url: <your url>
    topic: <your topic>
    username: <your username>
    password: <your password>
  telegram:
    token: <your api token>
    chatId: <your chat id>
  gotify:
    url: <your url>
    token: <your api token>

# Global configuration that applies to all tickets.
# These can be overridden on a ticket by ticket basis (see below).
# The below are examples for all global configuration settings.
# Remove the settings you do not need.
global:
  # Regions ticket listing must be for.
  # Defaults to all regions if not set.
  # Full list of regions can be seen here:
  # https://github.com/ahobsonsayers/twigots/blob/main/location.go#L79-L90
  regions:
    - GBLO # Only look for tickets in London

  # How similar the event name in the ticket listing must be to the one you specified.
  # Defaults to 0.85 if not set, to allow for naming inconsistencies.
  # Between 0-1
  eventSimilarity: 0.85

  # How many tickets must be in the listing.
  # Defaults to any number of tickets if not set.
  numTickets: 2

  # Minimum discount (including fees) the tickets in the listing
  # must have against the original price.
  # Defaults to any discount of tickets if not set.
  discount: 15

  # Notification services to send found tickets listings to.
  # Defaults to all configured services above.
  notification:
    - ntfy

# Ticket configuration.
# Settings set here take priority over global settings.
# If a setting is not set/specified here, global setting will be used
# To unset a global setting and use the default, set to a negative value or empty list depends on type
# The below are examples. Tweak them as needed
tickets:
  # Look for Lion King tickets using the global configuration.
  # For global configuration settings not set, defaults will be used.
  - event: Lion King # Required

  # Look for Taylor Swift tickets, overriding the global configuration.
  # of the defaults for settings not specified.
  - event: Taylor Swift # Required

    # Override global configuration setting
    # Event name must be an exact match
    # For example This will NOT match Taylor Swift: The Eras Tour
    eventSimilarity: 1

    # Override global configuration setting
    # Reset to default - watch for tickets from any region
    regions: []

    # Override global configuration setting
    # Reset to default - watch for tickets with ANY discount
    numTickets: -1

    # Override global configuration setting
    # Reset to default - watch for tickets with ANY discount
    discount: -1

    # Override global configuration setting
    # Send notifications to telegram (instead of notify)
    notification:
      - telegram

  # Look for Lion King tickets generally using the global configuration.
  # Notification will be sent to all notification services configures
  - event: Oasis # Required
    notification: []
