country: GB
regions: GBLO # TODO Currently ignored.
events:
  # Theatre
  - name: Back to the Future
  - name: Frozen
  - name: Hadestown
  - name: Hamilton
  - name: Harry Potter & the Cursed Child
  - name: Kiss Me Kate
  - name: Lion King
  - name: Matilda
  - name: Mean Girls
  - name: Moulin Rouge
  - name: My Neighbour Totoro
  - name: Operation Mincemeat
  - name: Starlight Express
  - name: Stranger Things
  - name: The Phantom Opera
  - name: The Wizard of Oz
  # Gigs
  - name: Coldplay
  - name: Gary Clark Jr.
  - name: Glass Animals
  - name: Jungle
  - name: Oasis
  - name: Taylor Swift
