# Docs: https://taskfile.dev/#/usage
version: "3"

tasks:
  lint:
    cmds:
      - golangci-lint run

  format:
    cmds:
      - go fmt ./...

  test:
    cmds:
      - |
        go clean -testcache
        go test ./...

  build:
    cmds:
      - go build -v -o ./bin/ ./cmd/twitchets

  build:docker:
    cmds:
      - docker build . -t arranhs/twitchets

  run:
    cmds:
      - go run ./cmd/twitchets

  run:docker:
    deps: [build:docker]
    cmds:
      - |
        docker run --rm \
          --name twitchets \
          -p 5656:5656 \
          arranhs/twitchets
