# Reusable Workflow for building and pushing a docker image
# https://docs.github.com/en/actions/using-workflows/reusing-workflows

name: Build and Push

on:
  workflow_call:
    inputs:
      commit:
        description: Full Commit Hash
        type: string
        required: true
      tags:
        description: Docker Image Tag(s)
        type: string
        required: true

jobs:
  build-push:
    name: Build and Push
    runs-on: ubuntu-latest
    timeout-minutes: 20
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get image tags
        id: tags
        run: |
          IFS=','
          read -r -a tags <<<"${{ inputs.tags }}"

          full_tags=()
          for tag in "${tags[@]}"; do
            full_tags+=("arranhs/twitchets:$tag")
          done

          echo "tags=${full_tags[*]}" >>"$GITHUB_OUTPUT"

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ${{ steps.tags.outputs.tags }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
